<h1>Modifier l'article</h1>

<div class="article-container">
  <div class="article-image">
    <?php if ($article->getImage()): ?>
      <img src="<?=asset('images/' . $article->getImage())?>" alt="">
    <?php endif; ?>
  </div>
  <div class="article-form">
    <!-- Formulaire de modification de l'article -->
    <form action="<?= constructUrl('admin_article_update', ['id' => $article->getIdArticle()]) ?>" method="POST" enctype="multipart/form-data">
      <div class="form-group">
        <label for="title">Titre</label>
        <input type="text" class="form-control" id="title" name="title" value="<?= $article->getTitle() ?>">
      </div>
      <div class="form-group">
        <label for="content">Contenu</label>
        <textarea class="form-control" id="content" name="content" rows="10"><?= $article->getContent() ?></textarea>
      </div>
      <div class="form-group">
        <label for="category">Catégorie</label>
        <select class="form-control" id="category" name="category">
          <?php foreach ($categories as $category) : ?>
            <option value="<?= $category->getIdCategory() ?>" <?= ($category->getIdCategory() == $article->getCategory()->getIdCategory()) ? 'selected' : '' ?>><?= $category->getName() ?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label for="image">Image</label>
        <input type="file" class="form-control-file" id="image" name="image">
      </div>
      <button type="submit" id="btn-update">Enregistrer les modifications</button>
    </form>
  </div>
</div>