<h1>Ajoutez un Article</h1>

<form class="form-add" enctype="multipart/form-data" action="<?=constructUrl('admin_article_new');?>" method="POST">
    <!-- <div> -->
      <label for="title">Titre :</label>
      
      <input type="text" id="title" name="title" value="<?=$title;?>">
      <?php if(isset($errors['title'])):?>
        <p class="error"><?=$errors['title'];?></p>
      <?php endif; ?>

      <label for="image">Image :</label>
      <input type="file" id="image" name="image">
      <?php if(isset($errors['image'])):?>
        <p class="error"><?=$errors['image'];?></p>
      <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="category">Catégorie :</label>
        <select name="category" id="category">
            <?php foreach ($categories as $category): ?>
                <option value="<?=intval($category->getIdCategory());?>"><?=htmlspecialchars($category->getName())?></option>
            <?php endforeach; ?>
        </select>
    <!-- </div>
    <div> -->
      <label for="content">Contenu :</label>
      <textarea id="content" name="content"><?=$content;?></textarea>
      <?php if(isset($errors['content'])):?>
        <p class="error"><?=$errors['content'];?></p>
      <?php endif; ?>
    <!-- </div> -->
    <input type="submit" value="Enregistrer" id="btn-add">
</form>