<h1>Modifier l'article</h1>

<div class="article">
      <div class="left">
      <?php if ($article->getImage()): ?>
                <img src="<?=asset('images/' . $article->getImage())?>" alt="">
            <?php endif; ?>
      </div>
      <div class="right">
      <small class="date"></small>Créé le <?=$article->getFormattedCreatedAt();?></small>
      <small class="category-title">   | |   <?=$article->getCategoryName();?></small>
        <h3><?=$article->getTitle();?></h3>
        <p class="card-text"><?=$article->getContent();?></p>
        
      </div>
        <!-- Formulaire de modification de l'article -->
        <form method="post" action="<?= constructUrl('admin_article_update', ['id' => $article->getIdArticle()]) ?>">
            <!-- Champs de saisie pour les attributs de l'article (titre, contenu, etc.) -->
            <div class="form-group">
                <label for="title">Titre</label>
                <input type="text" class="form-control" id="title" name="title" value="<?= $article->getTitle() ?>">
            </div>
            <div class="form-group">
                <label for="content">Contenu</label>
                <textarea class="form-control" id="content" name="content"><?= $article->getContent() ?></textarea>
            </div>
            <!-- Autres champs de saisie pour les attributs de l'article -->
            <!-- ... -->
            <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
        </form>
    </div>
</div>