<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog - YourTravel.fr </title>
  <link rel="stylesheet" href="<?=asset('css/style.css');?>">
  <link rel="icon" href="<?=asset('images/Yourtravel.fr.logo.png');?>" type="image/png">
  <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,700;1,300&family=Galada&family=Lemon&family=Prompt:wght@200;400&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"/>
</head>
<body>
  <nav>
    <div class="logo">
    <img src="<?=asset('images/Yourtravel.fr.logo.png');?>">
    <h1>Your Travel.fr</h1>
    </div>
    <div class="navbar-links">
    <?php $userSession = new App\Service\UserSession(); ?>
<?php if ($userSession->getUser() && $userSession->isAdmin()): ?>
    <a href="<?= constructUrl('admin_dashboard'); ?>">Administration</a>
    <a href="<?= constructUrl('logout'); ?>">Déconnexion</a>
<?php else: ?>
    <a href="<?= constructUrl('signup'); ?>">Inscription</a>
    <a href="<?= constructUrl('login'); ?>">Connexion</a>
<?php endif; ?>


    </div>
  </nav>
  
    <section class="articles">


    <!-- Message flash -->
    <?php if (isset($flashMessage) && $flashMessage): ?>
                <p class="success"><?=$flashMessage;?></p>
            <?php endif; ?>

      <!-- Contenu de la page --> 

      <?php include TEMPLATE_DIR . '/admin/' . $template . '.phtml'; ?>



    </section>
  
  <footer>
    
    <div class="social-media">
      <p><i class="fab fa-facebook"></i></p>
      <p><i class="fab fa-twitter"></i></p>
      <p><i class="fab fa-instagram"></i></p>
    </div>
    <p>@ Sebastien Lapeyre</p>
  </footer>
</body>
</html>