<!-- Le code HTML du corps de la page Article --> 
<div class="article">
      <div class="left">
      <?php if ($article->getImage()): ?>
                <img src="<?=asset('images/' . $article->getImage())?>" alt="">
            <?php endif; ?>
      </div>
      <div class="right">
      <small class="date"></small>Créé le <?=$article->getFormattedCreatedAt();?></small>
      <small class="category-title">   | |   <?=$article->getCategoryName();?></small>
        <h3><?=$article->getTitle();?></h3>
        <p class="card-text"><?=$article->getContent();?></p>
        
      </div>

      <div class="comment">
        <h2>Commentaires</h2>
        <form action="<?=constructUrl('article', ['id' => $idArticle])?>" method="POST">
            <fieldset>
                <legend>Ajouter un commentaire</legend>
                <div>
                    <label for="nickname">Pseudo</label>
                    <input type="text" id="nickname" name="nickname">
                    <?php if(isset($erros['nickname'])): ?>
                        <p class="error"><?=$errors['content']?></p>
                <?php endif; ?> 
                </div>
                <div>
                <label for="content">Commentaire</label>
                <textarea id="content" name="content"></textarea>
            </div>
            <input type="submit" value="Valider">
            </fieldset>
        </form>


        <?php if(empty($comments)): ?>
        <p>Soyez le premier à ajouter un commentaire !</p>
    <?php else: ?>
        <?php foreach ($comments as $comment): ?>
            <div>
                <h3>Ajouté par <?=$comment->getNickname();?> le <?=$comment->getFormattedCreatedAt();?></h3>
                <p><?=$comment->getContent();?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

      </div>