

<h1>Liste des catégories</h1>
<div id="search-container">
  <input type="text" id="search-input" placeholder="Rechercher une catégorie...">
  <ul id="search-results"></ul>
</div>


<div class="category-list">
    <?php foreach ($categories as $category): ?>
        <div class="category">
            <h2><?= $category->getName(); ?></h2>
            <!-- Autres informations de la catégorie -->
        </div>
    <?php endforeach; ?>
</div>

