<section class="contact-ctn"></section>

<h1>Contactez-nous</h1>
<p>Une Question ? Contactez nous directement !</p>

<form  action="<?=constructUrl('ajax-send-contact-form')?>" method="POST" id="contact-form">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>
    
    <label for="subject">Sujet:</label>
    <input type="text" id="subject" name="subject" required>
    
    <label for="content">Message:</label>
    <textarea id="content" name="content" required></textarea>
    
    <button id="btn-contact" type="submit">Envoyer</button>
</form>

</section>

<script src="<?=asset('js/contact.js');?>"></script>