<!-- login.phtml -->
<h2> Connexion :</h2>

<?php if($error != null) : ?>
    <p><?=$error;?></p>
<?php endif; ?>

<form id="login-form" action="<?= constructUrl('login') ?>" method="POST">
    <label for="username">Nom d'utilisateur :</label>
    <input type="text" id="username" name="username" required>
    
    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>
    
    <button type="submit">Se connecter</button>
</form>
