<!-- login.phtml -->
<h1>Connexion :</h1>

<?php if($error != null) : ?>
    <p><?=htmlspecialchars($error);?></p>
<?php endif; ?>

<form id="login-form" action="<?=htmlspecialchars(constructUrl('login'))?>" method="POST">
    <label for="username">Nom d'utilisateur :</label>
    <input type="text" id="username" name="username" required>
    
    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>
    
    <button id="btn-register" type="submit">Se connecter</button>
</form>
