<h1>Mon compte</h1>

<ul>
    <li>Nom d'utilisateur : <?= $user->getUsername() ?></li>
    <li>Prénom : <?= $user->getFirstname() ?></li>
    <li>Nom : <?= $user->getLastname() ?></li>
    <li>Email : <?= $user->getEmail() ?></li>
    <li>Pays : <?= $user->getCountry() ?></li>
    <li>Adresse : <?= $user->getAddress() ?></li>
    <li>Code postal : <?= $user->getPostalCode() ?></li>
</ul>

<a href="<?= constructUrl('update')?>">Modifier</a>