<!-- register.phtml -->
<form id="register-form" action="<?= constructUrl('process-registration') ?>" method="post">
    <label for="username">Nom d'utilisateur :</label>
    <input type="text" id="username" name="username" required>
    
    <label for="firstname">Prénom :</label>
    <input type="text" id="firstname" name="firstname" required>
    
    <label for="lastname">Nom :</label>
    <input type="text" id="lastname" name="lastname" required>
    

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>

    <label for="country">Pays :</label>
    <select id="country" name="country" required>
    <option value="">Sélectionnez un pays</option>
    <!-- Les options des pays seront ajoutées ici via JavaScript -->
    </select>

    <label for="address">Adresse :</label>
    <input type="text" id="address" name="address" required>
    
    <label for="postal_code">Code postal :</label>
    <input type="text" id="postal_code" name="postal_code" required>
    
    
    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>
    
    <button type="submit">S'inscrire</button>
</form>

<script src="<?=asset('js/CountryAPI.js');?>"></script>
      

