<!-- register.phtml -->
<h2>Inscription : </h2>

<form id="register-form" action="<?= constructUrl('signup') ?>" method="post">
<!-- <div> -->
        <label for="username">Nom d'utilisateur :</label>
        <input type="text" id="username" name="username" required value="<?= $username ?? '' ?>">
        <?php if (isset($errors['username'])) : ?>
            <p class="error"><?= $errors['username'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="firstname">Prénom :</label>
        <input type="text" id="firstname" name="firstname" value="<?= $firstname ?? '' ?>" required>
        <?php if (isset($errors['firstname'])) : ?>
            <p class="error"><?= $errors['firstname'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="lastname">Nom :</label>
        <input type="text" id="lastname" name="lastname" value="<?= $lastname ?? '' ?>" required>
        <?php if (isset($errors['lastname'])) : ?>
            <p class="error"><?= $errors['lastname'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" value="<?= $email ?? '' ?>" required>
        <?php if (isset($errors['email'])) : ?>
            <p class="error"><?= $errors['email'] ?></p>
        <?php endif; ?>
    <!-- </div> -->
    <!-- <div> -->
        <label for="country">Pays :</label>
        <select id="country" name="country" required>
        <option value="">Sélectionnez un pays</option>
    <!-- Les options des pays seront ajoutées ici via JavaScript -->
        </select>
    <!-- </div>
    <div> -->
        <label for="address">Adresse :</label>
       
        <input type="text" id="address" name="address" value="<?= $address ?? '' ?>" required>
        <?php if (isset($errors['address'])) : ?>
            <p class="error"><?= $errors['address'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="postal_code">Code postal :</label>
        <input type="text" id="postal_code" name="postal_code" value="<?= $postal_code ?? '' ?>" required>
        <?php if (isset($errors['postal_code'])) : ?>
            <p class="error"><?= $errors['postal_code'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>>
        <?php if (isset($errors['password'])) : ?>
            <p class="error"><?= $errors['password'] ?></p>
        <?php endif; ?>
    <!-- </div>
    <div> -->
        <label for="password-confirm">Confirmation du mot de passe :</label>
        <input type="password" id="password-confirm" name="password-confirm" required>
        <?php if (isset($errors['password-confirm'])) : ?>
            <p class="error"><?= $errors['password-confirm'] ?></p>
        <?php endif; ?>
    <!-- </div> -->
    
    <button id="btn-register" type="submit">S'inscrire</button>
</form>

<script src="<?=asset('js/CountryAPI.js');?>"></script>
      

