<!-- register.phtml -->
<h1>Inscription :</h1>

<form id="register-form" action="<?=htmlspecialchars(constructUrl('signup'))?>" method="post">
    <label for="username">Nom d'utilisateur :</label>
    <input type="text" id="username" name="username" required value="<?=htmlspecialchars($username ?? '')?>">
    <?php if (isset($errors['username'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['username'])?></p>
    <?php endif; ?>

    <label for="firstname">Prénom :</label>
    <input type="text" id="firstname" name="firstname" value="<?=htmlspecialchars($firstname ?? '')?>" required>
    <?php if (isset($errors['firstname'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['firstname'])?></p>
    <?php endif; ?>

    <label for="lastname">Nom :</label>
    <input type="text" id="lastname" name="lastname" value="<?=htmlspecialchars($lastname ?? '')?>" required>
    <?php if (isset($errors['lastname'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['lastname'])?></p>
    <?php endif; ?>

    <label for="email">Email :</label>
    <input type="email" id="email" name="email" value="<?=htmlspecialchars($email ?? '')?>" required>
    <?php if (isset($errors['email'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['email'])?></p>
    <?php endif; ?>

    <label for="country">Pays :</label>
    <select id="country" name="country" required>
        <option value="">Sélectionnez un pays</option>
        <!-- Les options des pays seront ajoutées ici via JavaScript -->
    </select>

    <label for="address">Adresse :</label>
    <input type="text" id="address" name="address" value="<?=htmlspecialchars($address ?? '')?>" required>
    <?php if (isset($errors['address'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['address'])?></p>
    <?php endif; ?>

    <label for="postal_code">Code postal :</label>
    <input type="text" id="postal_code" name="postal_code" value="<?=htmlspecialchars($postal_code ?? '')?>" required>
    <?php if (isset($errors['postal_code'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['postal_code'])?></p>
    <?php endif; ?>

    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>
    <?php if (isset($errors['password'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['password'])?></p>
    <?php endif; ?>

    <label for="password-confirm">Confirmation du mot de passe :</label>
    <input type="password" id="password-confirm" name="password-confirm" required>
    <?php if (isset($errors['password-confirm'])) : ?>
        <p class="error"><?=htmlspecialchars($errors['password-confirm'])?></p>
    <?php endif; ?>

    <button id="btn-register" type="submit">S'inscrire</button>
</form>

<script src="<?=htmlspecialchars(asset('js/CountryAPI.js'))?>"></script>
